### ISSUE TITLE
Expose a way to call formatList and showMore programatically

### ISSUE THREAD

**Issue by KidA78** [Traackr/jquery-plusmore#2]
Currently the plugin does a one time `formatList`, followed by the ability to `showMore`.  Of course a dev can write a custom functions for these options that can handle reformatting and showing more, however it would be a nice enhancement to expose a way to call the configured `showMore` and `formatList` methods programatically.

**Comment by sprak3000** [comment]
Resolved with release 2.0.0. New events added; see README.
